### ISSUE TITLE
Audio Dub for Easier Lipsync

### ISSUE THREAD

**Issue by Peekofwar** [Winded/StopMotionHelper#18]
It would be nice if we could place an audio file in the timeline to make animating someone talking a lot easier. Traditionally, we have to tab-out, and play the sound file several times, tab back into GMod, and try to get it right, or try and record the voice line in sync with the animation playing.

It would basically be an audio file that plays when scrubbing (like in Adobe Premiere) or at least during playback.

**Comment by Winded** [comment]
#21
