### ISSUE TITLE
TF2 Cosmetic Bug

### ISSUE THREAD

**Issue by ToxicHolyGrenade** [Winded/StopMotionHelper#86]
While the improved saving and loading ragdolls feature is a great thing, it unfortunately doesn't work for saved ragdolls that have merged cosmetics, specifically the TF2 characters. When loaded, the TF2 characters won't have their cosmetics applied at all. So is it possible to fix this issue?

**Comment by penolakushari** [comment]
SMH only spawns entities with modifiers that it can record to its keyframes. However I am not sure how to implement current spawning feature to work with bonemerged entities once parented stuff would be possible to select, so for current implementation it may not be done. You can just spawn a dupe from duplicator of a character you want and then apply the animation to it through the usual loading method.

**Comment by ToxicHolyGrenade** [comment]
So there is no way to really fix it basically speaking? What about using ChatGPT to fix those complications?

**Comment by ToxicHolyGrenade** [comment]
> SMH only spawns entities with modifiers that it can record to its keyframes. However I am not sure how to implement current spawning feature to work with bonemerged entities once parented stuff would be possible to select, so for current implementation it may not be done. You can just spawn a dupe from duplicator of a character you want and then apply the animation to it through the usual loading method.

So there is no way to really fix it basically speaking? What about using ChatGPT to fix those complications?

**Comment by MrTheshadowon** [comment]
Were you using the standard Bone Merge? It only works with Easy Bone Merge.

**Comment by ToxicHolyGrenade** [comment]
I am using Easy Bone Merge as opposed to the common Bone Merge tool, at least to confirm.

**Comment by MrTheshadowon** [comment]
I don't know how you broke it. Are you absolutely sure that you were using Easy Bone Merge? You sure you weren't using Composite Bone Tool (CBT)?

**Comment by penolakushari** [comment]
Quite sure what is meant there is the SMH's spawning thing, and it doesn't keep track of stuff that does not have smh keyframes, and it can't select bonemerged stuff so far, so, it doesn't spawn in merged stuff. Though I guess making some exceptions to be able to spawn those may be complicated, so probably just packing animations into dupes/gmod saves would be easier

**Comment by ToxicHolyGrenade** [comment]
> Quite sure what is meant there is the SMH's spawning thing, and it doesn't keep track of stuff that does not have smh keyframes, and it can't select bonemerged stuff so far, so, it doesn't spawn in merged stuff. Though I guess making some exceptions to be able to spawn those may be complicated, so probably just packing animations into dupes/gmod saves would be easier

So why not patch Stop Motion Helper? Because SMH is the most used compared to HAT and for good reason, and sadly there are no other great alternatives that would otherwise copy most of the stuff that SMH does. That's why I am wanting the addon to be overhauled accordingly at a certain later point, if not sooner.

**Comment by ToxicHolyGrenade** [comment]
> Quite sure what is meant there is the SMH's spawning thing, and it doesn't keep track of stuff that does not have smh keyframes, and it can't select bonemerged stuff so far, so, it doesn't spawn in merged stuff. Though I guess making some exceptions to be able to spawn those may be complicated, so probably just packing animations into dupes/gmod saves would be easier

It would also be quite a hassle having to find the correct items for a ragdoll, TF2 or otherwise, every time the items disappear. With a problem like this, it can put Gmod animation creators in a difficult position where they have to redo the scene all over again, and worse, being forced to do the project with no applied cosmetics at all. So can the tool be overhauled so this issue will be stripped out?

**Comment by penolakushari** [comment]
I'd suggest to just use gmod's saves and use the old way of loading SMH saves onto the ragdolls in the scene. Quite sure the tutorial for the thing on workshop page does go through how that works.

**Comment by ToxicHolyGrenade** [comment]
> I'd suggest to just use gmod's saves and use the old way of loading SMH saves onto the ragdolls in the scene. Quite sure the tutorial for the thing on workshop page does go through how that works.

I’m sorry, but those so-called solutions is like offering a rightfully angry customer complaining about a faulty product, and is instead being given useless solutions, since all they do is not only leave the customer in the dark, but also give the most regressive information possible that doesn’t truly fix the problem. My animation projects regarding my TF2 Freaks, are stuck in limbo for years, given the hardships I’ve faced in both real life and in the prism of the Gmod community for the most part.

That’s how I am feeling about this right now. If that is the direction the project is going, then I will officially say that this tool is not making much progress, even when compared to its more earlier versions. Now I am not going to say that I would rather have HAT or SMH destroyed, as it is a destruction of art, which is wrongful, but it will be very dickish and inconsiderate towards other Gmod animators.

But to be clear, I would rather regress myself and resort to physgun puppeteering rather than animation if the whole traction is to not actively evolve the tool so it is near-perfect at the very least, given the problems I and others are experiencing with it.

It is depressing that there are no superior alternatives either, even when it comes to more easy interface-based ones compared to Stop Motion Helper. I cannot use Source Filmmaker, because that’s not my profession. Besides, objectively, Gmod has more capabilities compared to SFM, whether we can see it or not. I would go out of my way to build my own animation tool for the community to use, even with similar features and a simple to use interface, but the thing is, I am not a programmer, or a computing expert.

What I would rather happen, is to return to the board and start over for the most part, without throwing everything within the source code completely out. And that way we can add more useful features and fixes like the one I want implemented, namely the disappearing items on ragdolls. We just need to return to basics and get to the bottom of what the root causes of those issues are.

**Comment by MrTheshadowon** [comment]
You're literally trying to sabotage Stop Motion Helper, that's all you are trying to do. You aren't a customer cause you aren't paying for it. At this point I'm thinking you are just wanting to make up things in order to have content creators to bend to your will, we aren't gonna do that. SMH is perfect as it is right now, and it doesn't need to be fixed with a non-existent problem. There is no solution to your issue because there is no issue.

**Comment by penolakushari** [comment]
Spawning feature in the current workshop version of SMH was not meant to be a total replacement for the loading stuff in, as it was mostly an experimental tool which also allows to spawn some of the animations with the position offset along with all of its positions, and it only works by spawning same class of entity with only data being transferred being the one that SMH keyframes themselves carry, so like positions, color, faceflexes and whatever stuff can be keyframed and was recorded in that animation. What is exactly hard with making a gmod save, which also allows you to keep all of your scenebuilding in + all of the models with stuff already bonemerged on them and then load animations onto them? I can admit that the process of loading stuff manually on each model can take some time if you got a lot of animated things, but that's how things worked since 2.0.

**Comment by ToxicHolyGrenade** [comment]
> You're literally trying to sabotage Stop Motion Helper, that's all you are trying to do. You aren't a customer cause you aren't paying for it. At this point I'm thinking you are just wanting to make up things in order to have content creators to bend to your will, we aren't gonna do that. SMH is perfect as it is right now, and it doesn't need to be fixed with a non-existent problem. There is no solution to your issue because there is no issue.

I am not sabotaging anything dude, so don't be a toxic moron jumping to conclusions. While I do feel like I am being put into a black hole where nothing occurs, all I am doing is making an analogy, not how I am a customer. Because that's not how the system works here. And given how you behave, you are gaslighting me on things contrary to what I am saying, which is not just unproductive, but also straight up ignorance. You should do yourself a favour, go onto Gmod, save an animation with the ragdolls having items intact, and load the animation again, and see if the problem gets recreated.

**Comment by ToxicHolyGrenade** [comment]
> Spawning feature in the current workshop version of SMH was not meant to be a total replacement for the loading stuff in, as it was mostly an experimental tool which also allows to spawn some of the animations with the position offset along with all of its positions, and it only works by spawning same class of entity with only data being transferred being the one that SMH keyframes themselves carry, so like positions, color, faceflexes and whatever stuff can be keyframed and was recorded in that animation. What is exactly hard with making a gmod save, which also allows you to keep all of your scenebuilding in + all of the models with stuff already bonemerged on them and then load animations onto them? I can admit that the process of loading stuff manually on each model can take some time if you got a lot of animated things, but that's how things worked since 2.0.

Having this kept since 2.0 doesn't have to be this way, because so long as that goes on, there will be those like myself, who will look back on the problems it might have. The disappearing items on ragdolls will definitely be one of them, especially the certain inefficiencies on that front. Sure, there have been improvements overtime, but from what I had observed, at least leaving aside the interface changes, there are issues that have been neglected, more specifically the disappearing items on ragdolls, which occurs every time I save and load the animation back up, and then boom, the items disappear.

My suggestion, is to go onto Gmod, spawn a ragdoll with items attached, make a very, very basic animation that doesn't take too long to do, save the animation, and then load it. And see if the problem occurs to you.

**Comment by penolakushari** [comment]
Never had that on my end. How are you loading the animation, exactly?

**Comment by MrTheshadowon** [comment]
I went into gmod and I think I know what you're doing.
![image](https://github.com/Winded/StopMotionHelper/assets/156720891/cb28c160-d2dc-4780-98c7-00242e84c3fe)
You're hitting the option that says spawn are you?

**Comment by ToxicHolyGrenade** [comment]
![hl2 2024-01-23 19-00-38-56](https://github.com/Winded/StopMotionHelper/assets/83011225/9ccad817-7f3d-49b3-a2ac-c83270f7a47a)
![hl2 2024-01-23 19-01-03-00](https://github.com/Winded/StopMotionHelper/assets/83011225/e19f6221-106e-4a9c-a366-b09bbba33026)
![hl2 2024-01-23 19-01-09-56](https://github.com/Winded/StopMotionHelper/assets/83011225/4c6b6d1e-9184-4c62-aa18-c0237c63f744)
![hl2 2024-01-23 19-01-13-02](https://github.com/Winded/StopMotionHelper/assets/83011225/ce4bef00-aa9f-45b1-a375-2549e7ad2351)
![hl2 2024-01-23 19-01-41-03](https://github.com/Winded/StopMotionHelper/assets/83011225/53c36c5c-f823-4175-b7f5-32fcd0a89391)
![hl2 2024-01-23 19-01-47-79](https://github.com/Winded/StopMotionHelper/assets/83011225/9352b1ac-f22c-401a-92bb-9a2fbea82581)

**Comment by ToxicHolyGrenade** [comment]
![hl2 2024-01-23 19-01-57-90](https://github.com/Winded/StopMotionHelper/assets/83011225/cba003ed-bba2-4f12-a8bf-094b60a2ac94)
![hl2 2024-01-23 19-08-45-41](https://github.com/Winded/StopMotionHelper/assets/83011225/2a6d83a1-0db1-4b0f-9e94-188179d3877a)
![hl2 2024-01-23 19-08-52-86](https://github.com/Winded/StopMotionHelper/assets/83011225/53626ff2-04db-493e-8fab-ea81efbc73ab)
![hl2 2024-01-23 19-09-01-31](https://github.com/Winded/StopMotionHelper/assets/83011225/a727da93-9ca1-4e72-aa64-4f7e51e39290)

**Comment by ToxicHolyGrenade** [comment]
![hl2 2024-01-23 19-09-06-75](https://github.com/Winded/StopMotionHelper/assets/83011225/3c4a82b7-908d-4d51-8365-5e8ae1f817d4)
![hl2 2024-01-23 19-09-13-35](https://github.com/Winded/StopMotionHelper/assets/83011225/b898bb76-4c7b-4dc6-b6a9-29e1d32a2e37)
![hl2 2024-01-23 19-09-18-11](https://github.com/Winded/StopMotionHelper/assets/83011225/b92d872b-7921-4c24-90ad-b5e04ee62439)
![hl2 2024-01-23 19-09-38-42](https://github.com/Winded/StopMotionHelper/assets/83011225/89150f97-6061-40a9-8d3c-f799d1517c8a)

**Comment by ToxicHolyGrenade** [comment]
![hl2 2024-01-23 19-09-40-69](https://github.com/Winded/StopMotionHelper/assets/83011225/8511df15-6b4b-42b6-ac65-3a016eb5becc)
![hl2 2024-01-23 19-09-56-52](https://github.com/Winded/StopMotionHelper/assets/83011225/9961dd82-d451-4d15-ac2a-cf5513aeb134)

**Comment by MrTheshadowon** [comment]
Wooooow, it's almost like there wasn't even a problem.
