### ISSUE TITLE
Compatibility with Collision Resizer

### ISSUE THREAD

**Issue by mrwallace888** [Winded/StopMotionHelper#89]
This supports Prop Resizer but I need Collision Resizer support (even if only using visual) because props with bones on them will scale all the bones up with Prop Resizer almost like using the inflate tool. But with Collision Resizer it scales the whole model up properly.

**Comment by penolakushari** [comment]
Quite sure that collision resizer creates a new entity which removes original one, so that removes all the recorded SMH keyframes from the original. All I can think of suggesting is to wait until next ragdoll mover update would be out, or grab its development version from github, as it has the ability to move scaled bones properly so it may achieve what you want in SMH-friendly way. (for ragdolls and physbones you may need to apply ragdoll stretch and weight modifiers which are 2 tools on workshop)

**Comment by mrwallace888** [comment]
Well that's kind of one of the things I was trying to figure out, that if I were to scale a model bone-by-bone, how would I go about fixing the bone positions post-scale? I wasn't sure if there was a math equation where like, for every x% increase/decrease, move a bone's position by y units, plus having to figure out how much offset to add on each positional axis.

**Comment by penolakushari** [comment]
Next update for ragdoll mover will have an option to exactly handle that

**Comment by mrwallace888** [comment]
And you said the GitHub for it already has it?

**Comment by penolakushari** [comment]
Yeah, I'm keeping new stuff mostly at my repo, though I do drop more or less stable stuff at Winded's one, though I didn't make a release for the version that's on workshop currently, oops. Oh well, next ragdoll mover update is about done, I just wanted to make some animation for a "public test" announcement that would also go over new additions. For now latest stuff is here, hopefully you'll figure out how some of the things work, there's also some options when you right click on the bones in the bone list now. https://github.com/penolakushari/RagdollMover/tree/fixes3

**Comment by mrwallace888** [comment]
Cool. I think one of the things I also wanted with Ragdoll Mover was manual values for phys bones or maybe like configurable angle snapping. Possibly maybe even symmetry too if applicable, though that would probably only work for humans and other models with the biped bones.

**Comment by penolakushari** [comment]
There is angle snapping feature, though it does get weird if you try to rotate something 180 degrees in one use with it, so it's better to do with 2 manipulations set to 90 degrees. Symmetry would require bones themselves to be angled correctly, though I am sure most models handle that, mirroring exists in modelling stuff after all. It should be possible, though I don't think I'll do that. So far only nonphysbones have adjustable sliders, whereas values for position of physbones may get rather large if we use their world coordinates, although I guess having some translations to parent bone's local systems would work too. But I think I'd leave implementation of that to someone else if they'd want to take it up, I don't think I'd use features like that much right now
